FROM golang:1.18 as build

WORKDIR /app

ADD main.go go.mod go.sum ./

RUN ls

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /main

FROM public.ecr.aws/lambda/go:1.2022.06.14.15
COPY --from=build /main /main

ENTRYPOINT ["/main"]
