
build:
	docker build --tag "deluser" .
push:
	docker tag  deluser:latest 118175606273.dkr.ecr.us-west-1.amazonaws.com/pomo-cafe-del-user:latest
	docker push 118175606273.dkr.ecr.us-west-1.amazonaws.com/pomo-cafe-del-user:latest